// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axtbjmbvcxeltsakkjoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4dGJqbWJ2Y3hlbHRzYWtram9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjI1MDgsImV4cCI6MjA2MTkzODUwOH0.G3hgbLQWybTyJrhv8XP6aBZDTIQZdq6eUsJOSG6mc1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);